name: QuizzedGame
description: The Perfect Quiz Game Ever.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^0.13.3
  firebase_auth: ^0.15.2
  provider: ^3.2.0
  random_string: ^2.0.1
  convex_bottom_bar: ^2.4.1
  fluttertoast: ^7.0.4
  get_it: ^4.0.1
  rflutter_alert: ^1.0.2
  data_connection_checker: ^0.3.4
  image_picker: ^0.6.0+17    
  firebase_storage: ^3.0.3
  string_validator: ^0.1.4
  
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - Assets/
   - lang/

  fonts:
  - family: Airbnb
    fonts:
    - asset: Assets/AirbnbCerealMedium.ttf